spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: vogistv@gmail.com
    password: Unity3D5XakasiyaS
  application:
    name: notification-service
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: *
            value:
              default:
                type: ru.leafall.notificationservice.dto.MailSenderMessage
