spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: idea-storage-service
              uri: lb://IDEA-STORAGE-SERVICE
              predicates:
                - Path=/idea-storage/**
              filters:
                - RewritePath=/idea-storage/(?<segment>.*), /$\{segment}
                - TokenValidation
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/account-service/**
              filters:
                - RewritePath=/account-service/(?<segment>.*), /$\{segment}
                - TokenValidation
            - id: file-service
              uri: lb://account-service
              predicates:
                - Path=/file-service/**
              filters:
                - RewritePath=/file-service/(?<segment>.*), /$\{segment}
                - TokenValidation

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka