spring:
  application:
    name: community-service
  datasource:
    username: myuser
    password: secret
    url: jdbc:postgres://127.0.0.1:5432/community_base
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    url: jdbc:postgres://127.0.0.1:5432/community_base
    driver-class-name: org.postgresql.Driver
    change-log: classpath:db/changelog/master.yml
    user: myuser
    password: secret
  jpa:
    show-sql: true
server:
  port: 8083
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
