services:
  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=community_base'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
