spring:

  application:
    name: file-service
  datasource:
    url: jdbc:postgres://127.0.0.1:5432/files_base
    password: files_base
    username: file_storage
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
    url: jdbc:postgres://127.0.0.1:5432/files_base
    password: files_base
    user: file_storage
  jpa:
    show-sql: true
  docker:
    compose:
      file: file-service/compose.yaml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
cloud:
  aws:
    credentials:
      accessKey: user-nrZBktwcDddd
      accessSecret: vcsXkdD6vv3wrF9fZ6Kcc1BVcTdWS9Fm
      region: ru-1
      endPoint: https://s3.buckets.ru/
      bucketName: leafallblyafbhjsdbnfdjhik
server:
  port: 8082