services:
  pg_protobin:
    image: "postgis/postgis:15-3.4"
    container_name: pg_protobin
    environment:
      - "POSTGRES_DB=pg_protobin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_USER=admin"
      - "TZ=UTC"
    ports:
      - "5433:5432"
  redis_protobin:
    image: "redis:6.0.16"
    container_name: redis_protobin
    command: ["redis-server", "--requirepass", "admin"]
    ports:
      - "6379:6379"
  redis-commander-protobin:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis_protobin
      REDIS_HOST: redis_protobin
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081